<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = Category::all();



        //dd($categories[0]->id);
        DB::table('products')->insert([
            [
                'name' => 'Plotery tnąco bigujący Graphtec FCX4000-50 ES',
                'index' => '001',
                'barcode'=>"111",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>50000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter płaski tnąco bigujący formar B2',
                'category_id'=>$categories[0]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FCX4000-50.jpg',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnąco bigujący Graphtec FCX4000-60 ES',
                'index' => '002',
                'barcode'=>"112",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>60000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter płaski tnąco bigujący formar B1',
                'category_id'=>$categories[0]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FCX4000-60.jpg',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
            'name' => 'Plotery tnąco bigujący Graphtec FCX2000-60 VC',
            'index' => '003',
            'barcode'=>"113",
            'quantity'=> 10,
            'unit'=>"szt.",
            'price'=>80000,
            'currency'=>"PLN",
            'vat_rate'=>23,
            'description'=>'Ploter płaski tnąco bigujący formar 60 x 92 cm',
            'category_id'=>$categories[0]->id,
            'priority'=>'a01',
            'active'=>true,
            'homePageActive'=>true,
            'image_path' => 'product/FCX2000-60.gif',
            'created_at' => date('y-m-d h:i:s'),
            'updated_at' => date('y-m-d h:i:s'),
             ],
            [
                'name' => 'Plotery tnąco bigujący Graphtec FCX2000-120 VC',
                'index' => '004',
                'barcode'=>"114",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>100000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter płaski tnąco bigujący formar 120 x 92 cm',
                'category_id'=>$categories[0]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FCX2000-120.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnąco bigujący Graphtec FCX2000-180 VC',
                'index' => '005',
                'barcode'=>"115",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>140000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter płaski tnąco bigujący formar 180 x 92 cm',
                'category_id'=>$categories[0]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FCX2000-180.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC9000-75',
                'index' => '006',
                'barcode'=>"116",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>10000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 75 cm',
                'category_id'=>$categories[1]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FC9000-75.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC9000-100',
                'index' => '007',
                'barcode'=>"117",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>15000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 100 cm',
                'category_id'=>$categories[1]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FC9000-100.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC9000-140',
                'index' => '008',
                'barcode'=>"118",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>25000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 140 cm',
                'category_id'=>$categories[1]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FC9000-140.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC9000-160',
                'index' => '009',
                'barcode'=>"119",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>35000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 160 cm',
                'category_id'=>$categories[1]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/FC9000-160.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC7000-40',
                'index' => '011',
                'barcode'=>"121",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>4000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 40 cm',
                'category_id'=>$categories[2]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/CE7000-40.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC7000-60',
                'index' => '012',
                'barcode'=>"122",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>7000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 60 cm',
                'category_id'=>$categories[2]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/CE7000-60.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC7000-130',
                'index' => '013',
                'barcode'=>"123",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>12000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 130 cm',
                'category_id'=>$categories[2]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/CE7000-130.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ],
            [
                'name' => 'Plotery tnący Graphtec FC7000-160',
                'index' => '014',
                'barcode'=>"124",
                'quantity'=> 10,
                'unit'=>"szt.",
                'price'=>20000,
                'currency'=>"PLN",
                'vat_rate'=>23,
                'description'=>'Ploter tnący rolkowy - obszar roboczy 160 cm',
                'category_id'=>$categories[2]->id,
                'priority'=>'a01',
                'active'=>true,
                'homePageActive'=>true,
                'image_path' => 'product/CE7000-160.gif',
                'created_at' => date('y-m-d h:i:s'),
                'updated_at' => date('y-m-d h:i:s'),
            ]


        ]);
    }
}
